# Generated by Django 5.0.3 on 2024-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affirmation', '0005_affirmationuser'),
        ('profiles', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='affirmation.category'),
        ),
    ]
