# Generated by Django 5.0.3 on 2024-04-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affirmation', '0005_affirmationuser'),
        ('profiles', '0003_profile_favorite_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_affirmations',
            field=models.ManyToManyField(blank=True, related_name='profile_affirmations', to='affirmation.affirmationuser'),
        ),
    ]
