# Generated by Django 5.0.3 on 2024-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affirmation', '0002_category_affirmation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmation',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
