# Generated by Django 5.0.3 on 2024-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affirmation', '0003_alter_affirmation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmation',
            name='text',
            field=models.CharField(max_length=800),
        ),
    ]
